Feature: Database Models & Protobufs
LimeChain/hedera-eth-bridge-validator pull request #167
Opened 2021-03-25 17:25 UTC by failfmi

**Detailed description**:
* Update `db` models
    * Update fields
    * Add relations between Transfer and Message
* Update `protobufs`
* Service: move `TransferData` to `transfer` service

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-03-26 09:54 UTC, georgiyazovaliiski commented on app/encoding/memo/memo.go
> +	// GasPrice the gas price that must be used in the mint transaction, converted to wei
Let's add that it is converted from Gwei to Wei

2021-03-26 10:10 UTC, georgiyazovaliiski submitted a review, later dismissed

2021-03-26 10:10 UTC, Daniel-K-Ivanov requested changes

2021-03-26 10:10 UTC, Daniel-K-Ivanov commented on app/persistence/transfer/transfer.go
>  const (
Since we are referring to the statuses outside this file, wouldn't it be better if we place them in the `entity` package -> `transfer`

2021-03-26 10:10 UTC, Daniel-K-Ivanov commented on app/process/recovery/recovery.go
> +		valid, targetAsset := r.contracts.IsValidBridgeAsset(asset)
Idea: Change the interface for retrieving the target asset to `r.contracts.ParseSourceAsset` or something similar and for it to return directly the asset. If an error is returned, we can think of it as the asset is unsupported

2021-03-29 10:42 UTC, Daniel-K-Ivanov approved these changes
LGTM!

2021-03-29 10:43 UTC, merged