E2e token transfer
LimeChain/hedera-eth-bridge-validator pull request #192
Opened 2021-04-07 06:45 UTC by Holymir

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #165 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-04-07 08:41 UTC, Daniel-K-Ivanov requested changes

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	// Step 1 - Verify the transfer of Hbars to the Bridge Account
nit: Shouldn't be `Hbars` but `HTS Token`

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	// Get bridge account hbar balance after transfer
shouldn't be `hbar` but `HTS token`

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	return *transactionResponse, whbarBalanceBefore
if we are not using `whbarBalanceBefore` why don't you remove it?

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	whbarBalanceBefore, err := setup.Clients.WTokenContract.BalanceOf(&bind.CallOpts{}, wTokenReceiverAddress)
this is not whbar. Its `wrappedToken`

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	case <-time.After(120 * time.Second):
if there a reason for the increased time here?

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
>  func sendHbarsToBridgeAccount(setup *setup.Setup, memo string) (*hedera.TransactionResponse, error) {
`sendHbarsToBridgeAccount` and `sendTokensToBridgeAccount` can be moved in `./clients/hedera.go` file. We will reduce the bloat in the main `e2e_test.go` file that way

2021-04-07 08:41 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	//TODO: submit the tx
You have to add a new function here: `verifyTransferFromAPI` that would:
1. Query the validator (add new function in the `./clients/validator.go` for querying the transfer data)
2. Verify the returned data

After that you can add the next step: `SubmitAndVerifyMint`, which would use the returned data from the validator API and call the contract mint function. 
Wait for the transaction to be successfully mined.
Verify the token balance of the receiver

2021-04-08 13:35 UTC, Daniel-K-Ivanov requested changes

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	// Step 1 - Verify the transfer of HTS Token to the Bridge Account
This test should be left to work with hbars. We can change the name to `Test_HBAR_No_Ethereum_TX_Submission` as-well

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	fmt.Println("transactionResponse:", transactionResponse.TransactionID)
this line is unnecessary maybe?

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	// Step 1 - Verify the transfer of Hbars to the Bridge Account
Should be `HTS` instead of `Hbars`

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	// tokenAddress, _ := setup.ParseToken(setupEnv.Clients.RouterContract, setupEnv.TokenID.String())
I guess this is unnecessary

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	// Get the wrapped hbar balance of the receiver before the transfer
`hbar` -> `hts token`

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +		log.Fatal(err)
should be `t.Fatal` i guess with a log

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +		if err != nil {
I think that we do not need the `if` here

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +	validateTokenBalance(setupEnv, wrappedTokenBalanceBefore, wTokenReceiverAddress, t)
Lets pack them into steps:
```
// Step 3 - Verify Transfer retrieved from Validator API
transactionData, tokenAddress := verifyTransferFromValidatorAPI(setupEnv, transactionResponse, receivedSignatures, t)

// Step 4 - Submit Mint transaction
txHash := submitMintTransaction(setupEnv, transactionResponse, transactionData, tokenAddress, t)

// Step 5 - Wait for transaction to be mined
waitForTransaction(setupEnv, txHash, t)

// Step 6 - Validate Token balances
validateTokenBalance(setupEnv, wrappedTokenBalanceBefore, wTokenReceiverAddress, t)

2021-04-08 13:35 UTC, Daniel-K-Ivanov commented on e2e/e2e_test.go
> +}
We should add one more step to verify DB records after execution. See the e2e test above.

```Go
// Step 7 - Verify Database records
expectedTxRecord := prepareExpectedTransfer(
		setupEnv.Clients.RouterContract,
		transactionResponse.TransactionID,
		nativeToken,
		"0",
		"0",
		database.ExpectedStatuses{
			Status:          entity_transfer.StatusCompleted,
			StatusSignature: entity_transfer.StatusSignatureMined,
		},
		ethTransactionHash,
		false, t)
	verifyDatabaseRecords(setupEnv.DbValidation, expectedTxRecord, receivedSignatures, t)
```

2021-04-08 14:40 UTC, Daniel-K-Ivanov commented
Lets resolve the E2E test before merging

2021-04-08 15:58 UTC, Daniel-K-Ivanov approved these changes

2021-04-09 07:10 UTC, georgiyazovaliiski requested changes

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +	tokensAmount := new(big.Int).SetInt64(int64(tokensSendAmount))
I think `big.NewInt(tokensSendAmount)` will do what you are looking for here.

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +		t.Fatalf("Incorect token balance")
`Incorrect token balance. Expected to be [%s], but was [%s].`

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +	}
Can we make the fatal logs a bit more descriptive, similar to this suggestion?
`Incorrect token balance. Expected to be [%s], but was [%s].`

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +	fmt.Printf("Token balance before transaction: [%s]\n", wrappedTokenBalanceBefore)
`fmt.Println(fmt.Sprintf())`

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +		t.Fatal(err)
We can merge these two lines into one: `t.Fatalf(`Unable to send Tokens to Bridge Account, Error: [%s]`, err)`

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +		t.Fatal(err)
Can we merge these two?

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +		t.Fatal(err)
Merge?

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +		t.Fatalf(`Expected to recieve the exact transfer amount of hbar: [%v]`, hBarSendAmount.AsTinybar())
recieve -> receive

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/e2e_test.go
> +		t.Fatalf(`Expected to recieve the exact transfer amount of hbar: [%v]`, hBarSendAmount.AsTinybar())
can we add, `but was [%v]`

2021-04-09 07:10 UTC, georgiyazovaliiski commented on e2e/setup/config.go
> +	keyTransactor, _ := signer.NewKeyTransactor(ethClient.ChainID())
```
if err != nil {
	return nil, err
}
```

2021-04-09 11:05 UTC, georgiyazovaliiski approved these changes

2021-04-12 12:50 UTC, Daniel-K-Ivanov approved these changes

2021-04-12 13:11 UTC, merged